apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
  labels:
    app: welcome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
        - name: welcome
          image: dragz17/sltr-devops-boy:latest
          ports:
            - containerPort: 5000
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: welcome-secret
                  key: DOCKER_USERNAME
            - name: DOCKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: welcome-secret
                  key: DOCKER_PASSWORD
