apiVersion: v1
kind: Secret
metadata:
  name: welcome-secret
type: Opaque
data:
  DOCKER_USERNAME: ZHJhZ3oxNwo= #<base64-encoded-username>
  DOCKER_PASSWORD: Q29kZUx5b2tvMTIzIUAj #<base64-encoded-password>
